// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjyzhgwiajobfpumeqvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqeXpoZ3dpYWpvYmZwdW1lcXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzExNzUsImV4cCI6MjA3MDgwNzE3NX0.Xe3u85nC62MQmJ-N6IDppr0orMOmBrwccTyIpQ0B_Hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});